### ISSUE TITLE
Add README with nbviewer links

### ISSUE THREAD

**Issue by scls19fr** [pydata/pydata-book#15]
Hello,

it will be nice to add nbviewer links for each IPython notebooks

http://nbviewer.ipython.org/github/pydata/pydata-book/blob/master/ch02.ipynb

http://nbviewer.ipython.org/github/pydata/pydata-book/blob/master/ch04.ipynb

http://nbviewer.ipython.org/github/pydata/pydata-book/blob/master/ch05.ipynb

http://nbviewer.ipython.org/github/pydata/pydata-book/blob/master/ch06.ipynb

http://nbviewer.ipython.org/github/pydata/pydata-book/blob/master/ch07.ipynb

http://nbviewer.ipython.org/github/pydata/pydata-book/blob/master/ch08.ipynb

http://nbviewer.ipython.org/github/pydata/pydata-book/blob/master/ch09.ipynb

http://nbviewer.ipython.org/github/pydata/pydata-book/blob/master/ch10.ipynb

http://nbviewer.ipython.org/github/pydata/pydata-book/blob/master/ch11.ipynb

http://nbviewer.ipython.org/github/pydata/pydata-book/blob/master/ch12.ipynb

http://nbviewer.ipython.org/github/pydata/pydata-book/blob/master/appendix_python.ipynb

http://nbviewer.ipython.org/github/pydata/pydata-book/blob/master/fec_study.ipynb

Thanks

**Comment by wesm** [comment]
done, thank you for the suggestion
