### ISSUE TITLE
Large file limit issue when cloning/pushing repo back to GitHub

### ISSUE THREAD

**Issue by eronlloyd** [pydata/pydata-book#18]
I just cloned this repo so I can work on it, which involves accessing it from multiple computers, all updated from a personal repo I use to keep everything synced. There is a file, https://github.com/pydata/pydata-book/blob/master/ch09/P00000001-ALL.csv, that is too large to push back to GutHub, so I'm wondering if you're using the new large file support, which is not accessible to everyone else yet without invites. I just put in a request for access, but in the meantime, I'm hoping for other suggestions.

Thanks!

**Comment by wesm** [comment]
Interesting — it might be that open source orgs are allowed to have larger repos. I'm open to storing the slug of data files someplace else (I could put them in my google drive or something) if that might help?

**Comment by eronlloyd** [comment]
I think I came up with a workaround, and it [looks like the official support] (https://github.com/blog/1986-announcing-git-large-file-storage-lfs) is on the way, so no worries. I can mark this closed unless you want to leave notice for other users.

Great book, by the way. I'm thoroughly enjoying it!

**Comment by wesm** [comment]
Strange -- maybe I never had a problem because I pushed the repo to this organization. If it becomes a problem I can look at hosting the large files in S3 and pruning them from this repo. Thanks
