### ISSUE TITLE
Some question about demo in p253

### ISSUE THREAD

**Issue by Lvnszn** [pydata/pydata-book#22]
I code p253 demo. When I ran it, it shown me error as below (python2.7 and ipython). Syntax error is tbilrate.
Could you please advice how to resolve it?

In [9]: data=macro[['cpi', 'm1, 'tbilrate', 'unemp']]
  File "<ipython-input-9-463e1c52ca12>", line 1
    data=macro[['cpi', 'm1, 'tbilrate', 'unemp']]

SyntaxError: invalid syntax

Many Thanks

**Comment by wesm** [comment]
'm1 is missing a closing parenthesis

**Comment by Lvnszn** [comment]
Thanks for your reminder, I should be more careful.
