### ISSUE TITLE
pydata-book/ch02.ipynb file apprears to be corrupted

### ISSUE THREAD

**Issue by yogibearforest** [pydata/pydata-book#27]
Unable to open the pydata-book/ch02.ipynb file.

Got the following error message when I click on the ch02.ipynb link in GitHub
![image](https://cloud.githubusercontent.com/assets/5693763/10181393/4534b96c-66cc-11e5-8f8e-a0f36f4d2188.png)

When loading into IPython Notebook from the downloaded zip file, get the following error.
![image](https://cloud.githubusercontent.com/assets/5693763/10181413/7de98a76-66cc-11e5-87e4-e268cd2a8b23.png)

Any suggestions?  Thanks.

**Comment by MrFroll** [comment]
Threre are two little bugs in JSON structure of ch02.ipynb: one extra comma and a comma is missing. You can fix this by hands as I did it here https://github.com/MrFroll/pydata-book/commit/b4fe591f24e735778e886308afd4e8f9456ead38.

**Comment by yogibearforest** [comment]
Your corrections fixed the problem.

Thank you very much.

**Comment by wesm** [comment]
thanks all, I have merged the fix
