### ISSUE TITLE
Python for Data Analysis directory names needs to change.

### ISSUE THREAD

**Issue by aybuketurker** [pydata/pydata-book#29]
MovieLens 1M Data Set
Page 23 -  the directory names

unames = ['user_id', 'gender', 'occupation', 'zip']
users = pd.read_table('movielens/users.dat,' sep= '::', header = None, names = unames)

USERS.DAT needs to change to ratings.dots
rnames = ['user_id', 'movie_id', 'rating', 'timestamp']
ratings = pd.read_table('movielens/users.dat', header = None, names = rnames )

USERS.DAT needs to change to movies.dots
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table(movielens/users.dat,header = None, names = mnames )

I believe I have the 2013 edition so if you guys already changed my apologies. this is a minor thing but might be annoying for beginners. 

great book! thank you so much!

**Comment by wesm** [comment]
Sorry about that. it's fixed in the notebooks here

https://github.com/pydata/pydata-book/blob/master/ch02.ipynb

If you find the error in a recent book edition can you please report on the O'Reilly errata page? Thanks
