### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by jharbert1** [pydata/pydata-book#31]
I'm new to your book and trying like crazy---but I seem to be missing a lot somewhere, somehow.
I hope you can help me.
I have tried to work through the usa.gov data from bit.ly and I always get no such file exists errors. The same goes for the movielens data...no matter how I try I get the same errors.
Am I supposed to download those files separately?
I've culled the net looking for better code but I figured you could point me in the right direction or tell me what I'm doing wrong?

Please help.  I would hate for this book to have been a terrible waste!!!

**Comment by wesm** [comment]
Hi!

Try downloading and unzipping this repository

https://github.com/pydata/pydata-book/archive/master.zip

After you unzip the directory and cd into it, you should see something like this:

```
09:17 ~/Downloads/pydata-book-master $ ll
total 452
-rw-r--r-- 1 wesm wesm 64732 Nov  6 14:28 appendix_python.ipynb
drwxr-xr-x 4 wesm wesm  4096 Nov  6 14:28 ch02/
-rw-r--r-- 1 wesm wesm 27762 Nov  6 14:28 ch02.ipynb
drwxr-xr-x 2 wesm wesm  4096 Nov  6 14:28 ch03/
-rw-r--r-- 1 wesm wesm 25525 Nov  6 14:28 ch04.ipynb
-rw-r--r-- 1 wesm wesm 47438 Nov  6 14:28 ch05.ipynb
drwxr-xr-x 2 wesm wesm  4096 Nov  6 14:28 ch06/
-rw-r--r-- 1 wesm wesm 19459 Nov  6 14:28 ch06.ipynb
drwxr-xr-x 2 wesm wesm  4096 Nov  6 14:28 ch07/
-rw-r--r-- 1 wesm wesm 46210 Nov  6 14:28 ch07.ipynb
drwxr-xr-x 3 wesm wesm  4096 Nov  6 14:28 ch08/
-rw-r--r-- 1 wesm wesm 22093 Nov  6 14:28 ch08.ipynb
drwxr-xr-x 2 wesm wesm  4096 Nov  6 14:28 ch09/
-rw-r--r-- 1 wesm wesm 33314 Nov  6 14:28 ch09.ipynb
-rw-r--r-- 1 wesm wesm 41086 Nov  6 14:28 ch10.ipynb
drwxr-xr-x 2 wesm wesm  4096 Nov  6 14:28 ch11/
-rw-r--r-- 1 wesm wesm 28260 Nov  6 14:28 ch11.ipynb
-rw-r--r-- 1 wesm wesm 24165 Nov  6 14:28 ch12.ipynb
drwxr-xr-x 2 wesm wesm  4096 Nov  6 14:28 ch13/
-rw-r--r-- 1 wesm wesm 21433 Nov  6 14:28 fec_study.ipynb
-rw-r--r-- 1 wesm wesm  1601 Nov  6 14:28 README.md
```

The files you're looking for are in these folders

```
09:17 ~/Downloads/pydata-book-master $ cd ch02/
09:18 ~/Downloads/pydata-book-master/ch02 $ ll
total 1572
drwxr-xr-x 2 wesm wesm    4096 Nov  6 14:28 movielens/
drwxr-xr-x 2 wesm wesm    4096 Nov  6 14:28 names/
-rw-r--r-- 1 wesm wesm 1598282 Nov  6 14:28 usagov_bitly_data2012-03-16-1331923249.txt
```

Let me know if this does not work for you.

**Comment by jharbert1** [comment]
Ok--thank you so much for getting back to me!
I have located the files...but will they work from the 'downloads' folder???
Don't I need them to be in the directory that I normally use to run python programs?
If so---how do I move them?

Thank you again.

**Comment by wesm** [comment]
You can change your current working directory using commands like this:

```
In [2]: import os

In [3]: os.path.expanduser('~/Downloads')
Out[3]: '/home/wesm/Downloads'

In [4]: os.chdir(os.path.expanduser('~/Downloads/pydata-book-master'))

In [5]: os.getcwd()
Out[5]: '/home/wesm/Downloads/pydata-book-master'
```

It may be different if you are using Windows, if so the operating system can give you the full path to your downloads directory

**Comment by jharbert1** [comment]
So far that seems to be working in ipython!
Thank you so much!

Question: How would I get this to run in a normal editor?

**Comment by jharbert1** [comment]
Also--do I have to use your method mentioned above each time I work in a new ipython shell?

**Comment by jharbert1** [comment]
In trying to run the program and get the horizantla bar graph---I got this:<matplotlib.axes._subplots.AxesSubplot at 0x109006e10>

Am I supposed to do something with that?

**Comment by wesm** [comment]
I recommend starting IPython from within the `pydata-book-master` directory that came out of the zip file. 

It's common to see console output like that from matplotlib; I would not be concerned with it. There may be some minor differences between things you see in the book and the current versions of the software -- the developers of the respective open source projects can help (either on GitHub or their mailing lists) if you need it.

**Comment by zhangjiantong** [comment]
In the cho7,how can deal with macrodata.csv like book?

**Comment by wesm** [comment]
See https://github.com/pydata/pydata-book/blob/master/ch07.ipynb

**Comment by yjonet** [comment]
Thank you, I have the same problem and now it's resolved.
