### ISSUE TITLE
CH08, column name conflicted with Dataframe's property

### ISSUE THREAD

**Issue by Morriaty-The-Murderer** [pydata/pydata-book#36]
There was one column named `size` in the file `ch08/tips.csv`.
```python
tips = pd.read_csv("tips.csv")
# The former one returned the property while I expected the column
tips.size
tips["size"]
```
So, I wanna know if there is any secure way to avoid this kind of conflicts.

**Comment by wesm** [comment]
The secure way is to always use `tips['size']`. But the attribute access is provided as an interactive convenience.
