### ISSUE TITLE
Ch 2, p. 24 error with code for operating_system

### ISSUE THREAD

**Issue by Elliebee79** [pydata/pydata-book#6]
Wes,

Can you clarify where the problem is with the error I got when typing in the equation for operating_system on p. 24?

Thanks

LEB

operating_system = np.where(cframe['a'].str.contains('Windows'),'Windows','Not Windows')

returned the following error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/Users/lauralea/Documents/pydata-book-master/<ipython-input-52-c0e5686563d8> in <module>()
----> 1 operating_system = np.where(cframe['a'].str.contains('Windows'),'Windows','Not Windows')

AttributeError: 'Series' object has no attribute 'str'

**Comment by tccyp001** [comment]
add this one  at the top 

import numpy as np

**Comment by choyccc** [comment]
thx

**Comment by wesm** [comment]
This requires newer versions of pandas. Using 0.16.2 or the latest 0.17.0 (as available in Anaconda or from PyPI) should work
